### PR TITLE
Fix duplicate virtualenv declaration

### PR DESCRIPTION
**Pull request by yrobla**
Tests on this module are failing with

Error: Cannot reassign variable virtualenv at
/etc/puppet/modules/python/manifests/virtualenv.pp:102

According to puppet, variable reassignment is not allowed:
https://docs.puppetlabs.com/puppet/latest/reference/
lang_variables.html#no-reassignment

Using a new var for the reassingment to avoid that problem

### CODE REVIEW

**Comment by shivapoudel** [comment]
@yrobla Do you need this for what?

**Comment by yrobla** [comment]
We are using this module on review.openstack.org.
We tried to bump to the latest version of the module , 1.9.2. My colleague @nibalizer sent a fix for that to correct paths yesterday and we wanted to use that. But when we applied that version into the tests, it's failing due to that reassignment of var. That's why i was trying to get that fixed.
Thanks

**Comment by shivapoudel** [comment]
cool!

**Comment by madphenomenon** [comment]
I have the same problem:
> Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Cannot reassign variable virtualenv at /etc/puppet/environments/testing/modules/python/manifests/virtualenv.pp:102 on node test

**Comment by madphenomenon** [comment]
@shivapoudel after upding https://forge.puppetlabs.com/stankevich/python to a 1.9.3 version I see the error:
> Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Syntax error at ';'; expected '}' at /etc/puppet/environments/testing/modules/python/manifests/virtualenv.pp:108 on node test

code in this line:
> 107    else {
> 108     $used_virtualenv = $virtualenv;
> 109   }
must be
> 107    else {
> 108     $used_virtualenv = $virtualenv,
> 109   }

**Comment by shivapoudel** [comment]
@madphenomenon this is shipped in `v1.9.4`. Please updated :)

**Comment by madphenomenon** [comment]
@shivapoudel thank you! :)

**Pull request merged**
