### PR TITLE
Ensure value is a string for =~ comparison

### PR DESCRIPTION
**Pull request by ghoneycutt**

### CODE REVIEW

**Comment by newbenji** [comment]
ah makes another problem

Error: Execution of '/bin/yum -d 0 -e 0 -y install ' returned 1: Error: Nothing to do
Error: /Stage[main]/Python::Install/Package[python]/ensure: change from purged to present failed: Execution of '/bin/yum -d 0 -e 0 -y install ' returned 1: Error: Nothing to do
Warning: /Stage[main]/Python::Install/Package[virtualenv]: Skipping because of failed dependencies
Warning: /Stage[main]/Python::Install/Package[pip]: Skipping because of failed dependencies
Error: Execution of '/bin/yum -d 0 -e 0 -y install -devel' returned 1: CRITICAL:yum.cli:Command line error: option -d: invalid integer value: 'evel'
Usage: yum [options] COMMAND

and the debug info
0;36mDebug: Package[python](provider=yum): Ensuring => presentESC[0m
ESC[0;36mDebug: Executing: '/bin/yum -d 0 -e 0 -y install 'ESC[0m
ESC[mNotice: /Stage[main]/Python::Install/Package[virtualenv]: Dependency Package[python] has failures: trueESC[0m
ESC[0;36mDebug: /Stage[main]/Python::Install/Package[virtualenv]: Resource is being skipped, unscheduling all eventsESC[0m
ESC[mNotice: /Stage[main]/Python::Install/Package[pip]: Dependency Package[python] has failures: trueESC[0m
ESC[0;36mDebug: /Stage[main]/Python::Install/Package[pip]: Resource is being skipped, unscheduling all eventsESC[0m
ESC[0;36mDebug: Executing: '/bin/rpm -q -devel --nosignature --nodigest --qf %{NAME} %|EPOCH?{%{EPOCH}}:{0}| %{VERSION} %{RELEASE} %{ARCH}\n'ESC[0m
ESC[0;36mDebug: Executing: '/bin/rpm -q -devel --nosignature --nodigest --qf %{NAME} %|EPOCH?{%{EPOCH}}:{0}| %{VERSION} %{RELEASE} %{ARCH}\n --whatprovides'ESC[0m
ESC[0;36mDebug: Package[python-dev](provider=yum): Ensuring => presentESC[0m
ESC[0;36mDebug: Executing: '/bin/yum -d 0 -e 0 -y install -devel'ESC[0m
ESC[0;36mDebug: Class[Python::Install]: Resource is being skipped, unscheduling all eventsESC[0m

**Comment by ghoneycutt** [comment]
Got this passing our tests. Could someone functionally test this change?

**Comment by newbenji** [comment]
Well the newest module version is working for me again on centos

**Comment by ghoneycutt** [comment]
Hi @newbenji Could you test this fork with python3 to ensure it works before I merge it

**Comment by newbenji** [comment]
i tested it before and i know its working.
The main reason for my error was faulty detection of python i think. so this was just a symptom.
i tried the 1.8.2 today and it worked
https://github.com/stankevich/puppet-python/commit/29aa2f316cd240cd68fe7ad63c719ee9b917509e
think this commit did it

**Pull request merged**
