### PR TITLE
Replaced --no-use-wheel with --no-binary :all: after installing lates…

### PR DESCRIPTION
**Pull request by chgarling**
…t pip version

### CODE REVIEW

**Comment by chgarling** [comment]
Hello, can you find some time to take a look at the outstanding pull requests, please?

**Comment by Mears148** [comment]
I would say you could fork if this becomes an ongoing support issue. This seems like a necessity at this point...anyone using pip v9 or newer cannot do installs now.

**Comment by flokli** [comment]
@chgarling Can you rebase this on master, as travis should be green now?

**Comment by chgarling** [comment]
@flokli I have rebased my changes on master right now. Please, can you check if its fine now, or if I have to do something else? I was not sure, if I need to create a new pull request after rebasing.

**Comment by flokli** [comment]
@chgarling you could simply squasch and force-push to the branch of this PR, but now this can also be squashed during merge. ping @ghoneycutt

**Comment by stankevich** [comment]
Replaced with https://github.com/stankevich/puppet-python/pull/388

**Pull request closed without merging**
