### PR TITLE
Add python3-venv as the $virtualenv_package for Ubuntu 16.04

### PR DESCRIPTION
**Pull request by rohankapoorcom**

### CODE REVIEW

**Comment by mgale** [comment]
Is anyone looking after this PR?

**Comment by djvdorp** [comment]
+1

**Comment by rohankapoorcom** [comment]
@stankevich @ghoneycutt Can one of you merge this in?

**Comment by stankevich** [comment]
Replaced with https://github.com/stankevich/puppet-python/pull/386

**Pull request closed without merging**
